package main

import (
	"database/sql"
	"fmt"
	_ "github.com/go-sql-driver/mysql"
)
func insertData(db *sql.DB) { //插入数据
	stmt, err := db.Prepare("insert into peter_user_tbl (username,password) values (?,?)") //Prepare creates a prepared statement for later queries or executions.
	checkErr(err)
	res, err := stmt.Exec("peteranderq", "377520") //Exec executes a prepared statement with the given arguments and returns a Result summarizing the effect of the statement.
	checkErr(err)
	id, err := res.LastInsertId() //LastInsertId returns the integer generated by the database in response to a command.
	checkErr(err)
	fmt.Println("Last insert id :", id)
}
func main() {
	db, err := sql.Open("mysql", "root:Aa1234567890.@/peter_backend?charset=utf8") //打开mysql数据库连接，并返回一个数据库句柄
	//     checkErr(err)
	insertData(db)
	err = db.Close() //Close closes the database, releasing any open resources.
	checkErr(err)
}
func checkErr(err error) {
	if err!= nil {
		panic(err)
	}
}